In [2]:
# Import required library
import numpy as np
import pandas as pd 
from scipy import stats


# Q1

In [2]:
#Q1.A F&B manager wants to determine whether there is any significant difference in the diameter of the cutlet between two units. A randomly selected sample of cutlets was collected from both units and measured? Analyze the data and draw inferences at 5% significance level. 
#Please state the assumptions and tests that you carried out to check validity of the assumptions.

In [5]:
# Loading dataset
cutlet_data=pd.read_csv("C:/Users/MANISHA/Downloads/Cutlets.csv")
cutlet_data.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [6]:
cutlet_data.tail()

Unit A  Unit B
30  6.7794  7.0992
31  7.2783  7.1180
32  7.1561  6.6965
33  7.3943  6.5780
34  6.9405  7.3875

In [8]:
# Define the hypothesis
#Ho:there is no difference in the diameter of the cutlet of unit A& unit B
#Ha:there is difference in the diameter of the cutlet of unit A& unit B.
# H0: μ1 = μ2 (No Difference in the Diameter)
# H1: μ1 ≠ μ2 (There is Difference in the Diameter)

In [10]:
# formula of P_value for two sample test
P_value=stats.ttest_ind(cutlet_data['Unit A'],cutlet_data['Unit B'])
P_value

Ttest_indResult(statistic=0.7228688704678061, pvalue=0.4722394724599501)

In [11]:
# if P_value<0.05 then reject the null hypothesis
# If P_value>0.05 then accept the null hypothesis
α = 0.05  # Standard
if P_value[1] < α:
    print('Reject the null hypothesis means there is difference in the diameter of the cutlet of unit A& unit B')
else:
    print('Accept the null hypothesis means there is no difference in the diameter of the cutlet of unit A&unit B')

Accept the null hypothesis means there is no difference in the diameter of the cutlet of unit A&unit B


# Q2.
A hospital wants to determine whether there is any difference in the average Turn Around Time (TAT) of reports of the laboratories on their preferred list. They collected a random sample and recorded TAT for reports of 4 laboratories. TAT is defined as sample collected to report dispatch.
   
Analyze the data and determine whether there is any difference in average TAT among the different laboratories at 5% significance level!

In [13]:
# L/d the/dataset
TAT=pd.read_csv("C:/Users/MANISHA/Downloads/LabTAT.csv")
TAT.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [14]:
# By using ANNOVA test,we can compare more than 2 features so defining the hypothesis
#Ho:μ1 = μ2 = μ3 = μ4 (No Difference in Average TAT)
#H1: μ1 = μ2 = μ3 ≠ μ (There is Difference in Average TAT)

In [16]:
# formula of ANNOVA test--give two value t-statistic and P-value
p_value=stats.f_oneway(TAT['Laboratory 1'],TAT['Laboratory 2'],TAT["Laboratory 3"],TAT["Laboratory 4"])
p_value

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [20]:
# Getting the using if conditions
α = 0.05  # Standard
if p_value[1] < α:
    print("The p_value is:",p_value[1],",Which is less then α, Reject H0, which means Atleast One is Different")
else:
    print("The p_value is:",p_value[1],",Which is greater then α, Fail to Reject H0, No Difference")


The p_value is: 2.1156708949992414e-57 ,Which is less then α, Reject H0, which means Atleast One is Different


# Q3.
Sales of products in four different regions is tabulated for males and females. Find if male-female buyer rations are similar across regions.


In [49]:
# Loading dataset
Buyer_Ratio=pd.read_csv('C:/Users/MANISHA/Downloads/BuyerRatio.csv')
Buyer_Ratio

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [23]:
# By using Chi-Square test we need to check the proportion between features.
# Define hypothesis
#Ho: All proportions are equal
#Ha: Not all proportions are equal.

In [50]:
# Library for chi-square
from scipy.stats import chi2_contingency

In [51]:
# Taking values in array format for observed values
Obs_value=np.array([[50,142,131,70],[435,1523,1356,750]])
Obs_value

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]])

In [53]:
#To get the Expected Value : 

# Using stats.chi2_contingency(crosstab) : this gives,chi square statistic,p_value & Expected value for observation
val=stats.chi2_contingency(Obs_value)

#chi square statistic,p_value & Expected value of Observed_values
val

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [54]:
# Getting Expected value from 'Val'
Expected_values=val[3]
Expected_values

array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]])

In [55]:
# Calculating degree of freedom
no_of_rows=len(Buyer_Ratio.iloc[0:2,0])
no_of_columns=len(Buyer_Ratio.iloc[0,0:4])
ddof=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:",ddof)
alpha = 0.05

Degree of Freedom: 3


In [56]:
#Calculating chi-square statistic for expected value
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(Obs_value,Expected_values)])
chi_square_statistic=chi_square[0]+chi_square[1]

In [57]:
#Printing value
print("chi-square statistic:-",chi_square_statistic)


chi-square statistic:- 1.5152956451130446


In [58]:
#calculating critical value
critical_value=chi2.ppf(q=1-alpha,df=ddof)
print('critical_value:',critical_value)

critical_value: 7.814727903251179


In [59]:
#p-value
p_value=1-chi2.cdf(x=chi_square_statistic,df=ddof)
print('p-value:',p_value)
print('Significance level: ',alpha)
print('Degree of Freedom: ',ddof)

p-value: 0.6787446296467897
Significance level:  0.05
Degree of Freedom:  3


In [60]:
if chi_square_statistic>=critical_value:
    print("Reject H0,Not All Proportions are Equal")
else:
    print("Fail to Reject H0,All Proportions are Equal")
    
if p_value<=alpha:
    print("Reject H0,Not All Proportions are Equal")
else:
    print("Fail to Reject H0,All Proportions are Equal")

Fail to Reject H0,All Proportions are Equal
Fail to Reject H0,All Proportions are Equal


# Q4.
TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain %  of the customer order forms. Any error in order form renders it defective and has to be reworked before processing.  The manager wants to check whether the defective %  varies by centre. Please analyze the data at 5% significance level and help the manager draw appropriate inferences.

In [3]:
# Loading the dataset
CustOF=pd.read_csv("C:/Users/MANISHA/Downloads/Costomer+OrderForm (1).csv")
CustOF.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [4]:
# All values are categorical hence using chi-square we will conclude the result
# Defining hypothesis
# Ho: Defective varies by Centre
# Ha: Defective not varies by centre

In [5]:
CustOF.Phillippines.value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [7]:
CustOF.Indonesia.value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [8]:
CustOF.Malta.value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [9]:
CustOF.India.value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [10]:
#Taking data into array for observed Value
Observed_Values = np.array([[271,267,269,280],[29,33,31,20]])
Observed_Values

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [12]:
#To get the Expected Value : 

# Using stats.chi2_contingency(crosstab) : this gives,chi square statistic,p_value & Expected value for observation
val=stats.chi2_contingency(Observed_Values)

#chi square statistic,p_value & Expected value of Observed_values
val

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

In [13]:
#Getting Expected Value from 'val' 
Expected_Values=val[3]
Expected_Values

array([[271.75, 271.75, 271.75, 271.75],
       [ 28.25,  28.25,  28.25,  28.25]])

In [17]:
#Calculating Degree of Freedom
no_of_rows=len(CustOF.iloc[0:2,0])
no_of_columns=len(CustOF.iloc[0,0:4])
ddof=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:",ddof)
alpha = 0.05

Degree of Freedom: 3


In [16]:
#Calculating chi-square statistic for expected value
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(Observed_Values,Expected_Values)])
chi_square_statistic=chi_square[0]+chi_square[1]

In [18]:
#Printing value
print("chi-square statistic:-",chi_square_statistic)

chi-square statistic:- 0.9036806669326146


In [19]:
#calculating critical value
critical_value=chi2.ppf(q=1-alpha,df=ddof)
print('critical_value:',critical_value)

critical_value: 7.814727903251179


In [20]:
#p-value
p_value=1-chi2.cdf(x=chi_square_statistic,df=ddof)
print('p-value:',p_value)
print('Significance level: ',alpha)
print('Degree of Freedom: ',ddof)

p-value: 0.8245394896914965
Significance level:  0.05
Degree of Freedom:  3


In [21]:
if chi_square_statistic>=critical_value:
    print("Reject H0, Defective Not Varies By Centre")
else:
    print("Fail to Reject H0, Defective Varies By Centre")
    
if p_value<=alpha:
    print("Reject H0, Defective Not Varies By Centre")
else:
    print("Fail to Reject H0, Defective Varies By Centre")

Fail to Reject H0, Defective Varies By Centre
Fail to Reject H0, Defective Varies By Centre
